// src/services/authService.ts
import api from './api';
import type { User, AuthResponse } from '@/types'; // Using path alias

// Type for login credentials
interface LoginCredentials {
  email: string;
  password: string;
}

// Type for signup data (excluding _id, which is generated by backend)
interface SignupData {
  username: string;
  email: string;
  password: string;
}

export const loginUser = async (credentials: LoginCredentials): Promise<AuthResponse> => {
  const response = await api.post<AuthResponse>('/auth/login', credentials);
  return response.data;
};

export const signupUser = async (userData: SignupData): Promise<AuthResponse> => {
  const response = await api.post<AuthResponse>('/auth/signup', userData);
  return response.data;
};

export const getMe = async (): Promise<User> => {
  const response = await api.get<User>('/auth/me');
  return response.data;
};